# Header
menu:
  主页: /
  前端挖掘: /categories/fedev/
  iOS爱好: /categories/iosdev/
  android兴趣: /categories/androidev/
  cocos2dx研究: /categories/cocos2dx/
  unity3d趋势: /categories/unity3d/
  PHP小抄: /categories/php/
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://gihub.com/kinglion"
  weibo: "http://weibo.com/u/1288784635"
  rss: "/atom.xml"
  facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
google_analytics: '<script src="http://s4.cnzz.com/z_stat.php?id=1254117900&web_id=1254117900" language="JavaScript"></script>'
favicon: /favicon.png

#你的头像
avatar: "https://avatars1.githubusercontent.com/u/3380489?v=3&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  个人github: http://github.com/kinglion
  ChrisCheung: http://daddybh.github.io
  lisarao: http://lisarao.github.io/blog
  blackie4: http://kuscript.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 前端挖掘机…