# Header
menu:
  主页: /
  前端挖掘: /fedev
  iOS爱好: /iosdev
  android兴趣: /androidev
  cocos2dx研究: /cocos2dx
  unity3d趋势: /unity3d
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://gihub.com/kinglion"
  weibo: "http://weibo.com/u/1288784635"
  rss: "/atom.xml"
  facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像
avatar: "http://chuantu.biz/t/62/1421674910x1822613108.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  个人github: https://blog.lncoder.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 前端挖掘机…